name: Python tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
        # python-version: ["3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v3

      - name: Install system dependencies (OpenGL for gmsh)
        run: sudo apt-get update && sudo apt-get install -y libglu1-mesa

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.8.3"

      - name: Install dependencies
        run: poetry install

      - name: Run tests with coverage
        run: PYTHONPATH=scikit-topt poetry run pytest --cov=sktopt --cov-report=xml
