name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.8.3"

      - name: Install dependencies
        run: poetry install --no-root

      - name: Build with Poetry
        run: poetry build

      - name: Publish to PyPI with token
        run: poetry publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
